name: MyCrazyRPG
main: eu.around_me.rpgplugin.RPGPluginMain
version: 0.1
commands:
  skillbind:
    description: Bind a skill to a item
    usage: /skillbind [skillname]
  togglesidebar:
    description: Hides/Shows the sidebar
    usage: /togglesidebar
  showskillmenu:
    description: Show the Skill Menu
    usage: /showskillmenu    
  sidebardisplay:
    description: Toggle absolute values in the Sidebar
    usage: /sidebardisplay [toggleabs]    
  dbgcmd:
    description: Admin Commands
    usage: /dbgcmd [crit|evasion]    